#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

# 非合并代码的commit才需要检查
if ! echo "$commit_msg" | grep -qE "^Merge branch "; then
    node .husky/commit-check.js $1
fi

npm run lint-staged
